name: demo pipeline

on:
  push:
    branches: patch
  
jobs:
  build:
    name: test
    runs_on: ubuntu latest
    steps:
     - uses: actions/checkout

       name: run one line script
       run: echo Hello world!