name: demo

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo Hello world!

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{github.workspace}}
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ${{github.workspace}}